import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import { NavBar } from "@/components/NavBar";
import { cn } from "@/lib/utils";
import Providers from "@/lib/providers";
import { Toaster } from "sonner";

const inter = Inter({ subsets: ["latin"], preload: true });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="bg-foreground text-foreground dark">
      <body className={cn("h-full font-sans antialiased", inter.className)}>
        <Providers>
          <NavBar />
          <main className="relative mx-auto flex min-h-screen flex-col px-4 md:px-12">
            {children}
            <Toaster richColors />
          </main>
        </Providers>
      </body>
    </html>
  );
}
